services:
  retro-micro-emulator:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_SANDBOX_HOSTNAME: buildkitsandbox
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "5173:5173"
    restart: unless-stopped
    volumes:
      # Reactソース共有
      - ./src:/usr/app/ReactEmu/src
      - ./tsconfig.json:/usr/app/ReactEmu/tsconfig.json
      - ./vite.config.ts:/usr/app/ReactEmu/vite.config.ts
